{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.river;

  # River init script content
  riverInitScript = ''
    #!/bin/sh

    # River WM configuration
    # Generated by Home Manager

    # === Gruvbox Dark Medium Colors ===
    # base00: 282828 (bg)      base08: fb4934 (red)
    # base01: 3c3836           base09: fe8019 (orange)
    # base02: 504945           base0A: fabd2f (yellow)
    # base03: 665c54           base0B: b8bb26 (green)
    # base04: bdae93           base0C: 8ec07c (cyan)
    # base05: d5c4a1 (fg)      base0D: 83a598 (blue)
    # base06: ebdbb2           base0E: d3869b (magenta)
    # base07: fbf1c7           base0F: d65d0e (brown)

    # === Environment Variables ===
    export XDG_CURRENT_DESKTOP=river
    export XDG_SESSION_TYPE=wayland
    export XDG_SESSION_DESKTOP=river
    export MOZ_ENABLE_WAYLAND=1
    export QT_QPA_PLATFORM="wayland;xcb"
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
    export GDK_BACKEND="wayland,x11"
    export SDL_VIDEODRIVER=wayland
    export CLUTTER_BACKEND=wayland
    export WLR_NO_HARDWARE_CURSORS=1
    export LIBVA_DRIVER_NAME=radeonsi
    export XCURSOR_SIZE=24
    export XCURSOR_THEME=Adwaita

    # === Export environment to systemd/dbus for portals ===
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
    systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE

    # === Mod Key ===
    mod="Super"

    # === Basic Settings ===
    riverctl border-width 2
    riverctl set-cursor-warp on-focus-change

    # === Border Colors (Gruvbox) ===
    riverctl border-color-focused 0x${cfg.borderColorFocused}
    riverctl border-color-unfocused 0x${cfg.borderColorUnfocused}
    riverctl border-color-urgent 0xfb4934

    # === Input Configuration ===
    riverctl input "*" accel-profile flat
    riverctl input "*" tap enabled
    riverctl input "type:keyboard" repeat-delay ${toString cfg.keyboardRepeatDelay}
    riverctl input "type:keyboard" repeat-rate ${toString cfg.keyboardRepeatRate}

    # === Window Focus (vim-style) ===
    riverctl map normal $mod H focus-view left
    riverctl map normal $mod J focus-view down
    riverctl map normal $mod K focus-view up
    riverctl map normal $mod L focus-view right

    # === Window Swap ===
    riverctl map normal $mod+Shift H swap left
    riverctl map normal $mod+Shift J swap down
    riverctl map normal $mod+Shift K swap up
    riverctl map normal $mod+Shift L swap right

    # === Window Actions ===
    riverctl map normal $mod Q close
    riverctl map normal $mod F toggle-fullscreen
    riverctl map normal $mod Space toggle-float

    # === Layout Control (wideriver) ===
    riverctl map normal $mod+Control H send-layout-cmd wideriver "--ratio -0.05"
    riverctl map normal $mod+Control L send-layout-cmd wideriver "--ratio +0.05"
    riverctl map normal $mod M send-layout-cmd wideriver "--layout monocle"
    riverctl map normal $mod T send-layout-cmd wideriver "--layout left"
    riverctl map normal $mod Tab send-layout-cmd wideriver "--layout-toggle"

    # === Multi-Monitor Navigation ===
    # River uses global tags (not per-monitor workspaces like Sway/i3)
    # Recommended workflow for dual-monitor setup:
    #   Tags 1-5: Primary monitor (HDMI-A-1 ultrawide)
    #   Tags 6-9: Secondary monitor (DP-2 portrait)
    # 
    # Focus next/previous monitor
    riverctl map normal $mod Comma focus-output previous
    riverctl map normal $mod Period focus-output next

    # Send focused window to next/previous monitor (and follow it)
    riverctl map normal $mod+Shift Comma send-to-output previous
    riverctl map normal $mod+Shift Period send-to-output next

    # Send window to monitor without following (stay on current monitor)
    riverctl map normal $mod+Control Comma send-to-output --current-tags previous
    riverctl map normal $mod+Control Period send-to-output --current-tags next

    # === Tags (Workspaces 1-9) ===
    for i in $(seq 1 9); do
        tags=$((1 << ($i - 1)))
        riverctl map normal $mod $i set-focused-tags $tags
        riverctl map normal $mod+Shift $i set-view-tags $tags
        riverctl map normal $mod+Control $i toggle-focused-tags $tags
        riverctl map normal $mod+Control+Shift $i toggle-view-tags $tags
    done

    # All tags (tag 0 = all)
    all_tags=$(((1 << 9) - 1))
    riverctl map normal $mod 0 set-focused-tags $all_tags
    riverctl map normal $mod+Shift 0 set-view-tags $all_tags

    # === Scratchpad (tag 21, outside normal 1-9 workspaces) ===
    scratch_tag=$((1 << 20))
    riverctl map normal $mod P toggle-focused-tags ''${scratch_tag}
    riverctl map normal $mod+Shift P set-view-tags ''${scratch_tag}
    all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
    riverctl spawn-tagmask ''${all_but_scratch_tag}

    # === App Launchers ===
    riverctl map normal $mod Return spawn ${cfg.terminal}
    riverctl map normal $mod A spawn fuzzel
    riverctl map normal $mod B spawn firefox
    riverctl map normal $mod E spawn "${cfg.terminal} -e fish -c yazi"

    # === Screenshots (grim + slurp) ===
    riverctl map normal None Print spawn ~/.local/bin/screenshot-area
    riverctl map normal $mod+Shift S spawn ~/.local/bin/screenshot-area
    riverctl map normal Control Print spawn ~/.local/bin/screenshot-screen
    riverctl map normal Shift Print spawn ~/.local/bin/screenshot-save

    # === Screen Recording (wf-recorder) ===
    riverctl map normal $mod R spawn ~/.local/bin/screenrecord-area
    riverctl map normal $mod+Control R spawn ~/.local/bin/screenrecord-screen
    riverctl map normal $mod+Shift R spawn ~/.local/bin/screenrecord-save

    # === Clipboard History ===
    riverctl map normal $mod V spawn 'cliphist list | fuzzel --dmenu | cliphist decode | wl-copy'

    # === Screen Lock ===
    riverctl map normal $mod Escape spawn waylock

    # === Power Menu ===
    riverctl map normal $mod+Shift E spawn wlogout

    # === Floating TUI Apps ===
    riverctl map normal $mod+Shift B spawn "${cfg.terminal} --title=btop -e btop"
    riverctl map normal $mod+Shift T spawn "${cfg.terminal} --title=bluetuith -e bluetuith"
    riverctl map normal $mod+Shift W spawn "${cfg.terminal} --title=impala -e impala"

    # === Display Management ===
    riverctl map normal $mod+Control D spawn wdisplays
    riverctl map normal $mod+Control M spawn "kanshictl reload"

    # === Notification Control ===
    riverctl map normal $mod N spawn "fnottctl dismiss"
    riverctl map normal $mod+Shift N spawn "fnottctl dismiss all"

    # === Media Keys ===
    riverctl map normal None XF86AudioRaiseVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map normal None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map normal None XF86AudioMicMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'
    riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map normal None XF86AudioPause spawn 'playerctl play-pause'
    riverctl map normal None XF86AudioNext spawn 'playerctl next'
    riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
    riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
    riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    # === Mouse Bindings ===
    riverctl map-pointer normal $mod BTN_LEFT move-view
    riverctl map-pointer normal $mod BTN_RIGHT resize-view
    riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

    # === Focus follows mouse ===
    riverctl focus-follows-cursor normal

    # === Window Rules ===
    riverctl rule-add -app-id 'btop' float
    riverctl rule-add -app-id 'bluetuith' float
    riverctl rule-add -app-id 'impala' float
    riverctl rule-add -app-id 'pavucontrol' float
    riverctl rule-add -app-id 'nm-connection-editor' float
    riverctl rule-add -app-id '.blueman-*' float
    riverctl rule-add -app-id 'org.gnome.Calculator' float

    # === Autostart ===
    # Layout generator (wideriver - dwm/xmonad style)
    riverctl spawn "wideriver --layout left --stack dwindle --count-master 1 --ratio-master 0.55 --border-width 2 --border-width-monocle 0 --inner-gap 0 --outer-gap 0"

    # Wallpaper - Solid gruvbox background color (#282828)
    riverctl spawn "swaybg -c '#282828'"

    # Notifications
    riverctl spawn fnott

    # Clipboard watchers
    riverctl spawn "wl-paste --type text --watch cliphist store"
    riverctl spawn "wl-paste --type image --watch cliphist store"

    # Night light
    riverctl spawn gammastep

    # Network/Bluetooth tray
    riverctl spawn "nm-applet --indicator"
    riverctl spawn blueman-applet

    # Polkit agent
    riverctl spawn "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1"

    # Auto display management
    riverctl spawn kanshi

    # === Default layout generator ===
    riverctl default-layout wideriver
  '';

in {
  options.programs.river = {
    enable = mkEnableOption "River Wayland compositor";

    terminal = mkOption {
      type = types.str;
      default = "ghostty";
      description = "Default terminal emulator";
    };

    borderColorFocused = mkOption {
      type = types.str;
      default = "83a598";
      description = "Border color for focused windows (hex without 0x prefix)";
    };

    borderColorUnfocused = mkOption {
      type = types.str;
      default = "504945";
      description = "Border color for unfocused windows (hex without 0x prefix)";
    };

    keyboardRepeatDelay = mkOption {
      type = types.int;
      default = 250;
      description = "Keyboard repeat delay in milliseconds";
    };

    keyboardRepeatRate = mkOption {
      type = types.int;
      default = 30;
      description = "Keyboard repeat rate";
    };
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      # River and layout manager
      river-classic
      wideriver
      wlr-randr

      # Wayland tools
      grim
      slurp
      wf-recorder
      wl-clipboard
      cliphist
      wdisplays

      # UI applications
      fuzzel
      fnott
      waylock
      wlogout
      swaybg      # Solid color wallpaper
      gammastep

      # System utilities
      polkit_gnome
      networkmanagerapplet
      blueman
      impala        # TUI wifi manager
      bluetuith     # TUI bluetooth manager
      pavucontrol   # PulseAudio volume control

      # Additional dependencies for keybindings
      playerctl
      brightnessctl
      wireplumber  # for wpctl
      kanshi
    ];

    xdg.configFile."river/init" = {
      text = riverInitScript;
      executable = true;
    };
  };
}
